### ISSUE TITLE
"ReferenceError: document is not defined" when I use Select component with Nuxt.js

### ISSUE THREAD

**Issue by kieusonlam** [rafaelpimpa/buefy#29]
I just copy and paste example code into my Nuxt.js project, and I got this error.

```
Nuxt.js Error:

ReferenceError: document is not defined
    at VueComponent.created (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\buefy\lib\src\index.js:3:1086)
    at callHook (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue\dist\vue.runtime.common.js:2271:21)
    at VueComponent.Vue._init (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue\dist\vue.runtime.common.js:3754:5)
    at new VueComponent (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue\dist\vue.runtime.common.js:3918:12)
    at createComponentInstanceForVnode (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue-server-renderer\build.js:5182:10)
    at renderComponent (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue-server-renderer\build.js:6696:40)
    at RenderContext.renderNode (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue-server-renderer\build.js:6681:7)
    at RenderContext.next (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue-server-renderer\build.js:169:14)
    at cachedWrite (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue-server-renderer\build.js:30:9)
    at RenderContext.renderNode (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue-server-renderer\build.js:6689:7)
    at RenderContext.next (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue-server-renderer\build.js:169:14)
    at RenderContext.cachedWrite [as write] (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue-server-renderer\build.js:30:9)
    at RenderContext.next (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue-server-renderer\build.js:172:14)
    at cachedWrite (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue-server-renderer\build.js:30:9)
    at RenderContext.renderNode (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue-server-renderer\build.js:6689:7)
    at RenderContext.next (C:\Users\xxxxxxxxxx\Desktop\testapp\node_modules\vue-server-renderer\build.js:169:14)
```

**Comment by rafaelpimpa** [comment]
Buefy is not optimized for SSR and I don't have the intention to do so in the near future.

**Comment by kieusonlam** [comment]
Thanks for awsering. I think they are not available. Anyway everything else is working perfectly, so I may replace it with Ratio button.

P/S: I'm trying to create a blog, I think SSR is useful for me at least. I will look for SSR fully supported in the future.

**Comment by rafaelpimpa** [comment]
SSR is great for the open web / blog! I just don't have the time to work on it right now, this lib (Buefy) I started cause I'm gonna use it on a bigger project I'm working on, and it's not open web. Gotta focus on that first :)
