### ISSUE TITLE
 Undefined variable: "$weight-semibold".

### ISSUE THREAD

**Issue by codeitlikemiley** [rafaelpimpa/buefy#79]
Hi im using latest buefy, and i am compiling with laravel mix...

the normal workflow is like so

add your scss custom in your app.scss
which will be compiled by your laravel mix

this is my app.scss
```
@import url(https://fonts.googleapis.com/icon?family=Material+Icons);
@import "core";
```
The core Scss is the custom Styling i copy from the documentation
_core.scss 
```
// Import Bulma's core
@import "~bulma/sass/utilities/_all";

// Set your colors
$primary: #8c67ef;
$primary-invert: findColorInvert($primary);
$twitter: #4099FF;
$twitter-invert: findColorInvert($twitter);

// Setup $colors to use as bulma classes (e.g. 'is-twitter')
$colors: (
    "white": ($white, $black),
    "black": ($black, $white),
    "light": ($light, $light-invert),
    "dark": ($dark, $dark-invert),
    "primary": ($primary, $primary-invert),
    "info": ($info, $info-invert),
    "success": ($success, $success-invert),
    "warning": ($warning, $warning-invert),
    "danger": ($danger, $danger-invert),
    "twitter": ($twitter, $twitter-invert)
);

// Links
$link: $primary;
$link-invert: $primary-invert;
$link-focus-border: $primary;

// Import Bulma and Buefy styles
@import "~bulma";
@import "~buefy/src/scss/buefy";
```

when i run npm run hot

```
 ERROR  Failed to compile with 3 errors                                                                                                              7:48:09 AM

 error  in ./resources/assets/sass/app.scss

Module build failed: ModuleBuildError: Module build failed:
        font-weight: $weight-semibold;
                    ^
      Undefined variable: "$weight-semibold".
      in /mnt/c/Users/uriah/sites/www/fb/node_modules/buefy/src/scss/components/_dialog.scss (line 24, column 22)
    at runLoaders (/mnt/c/Users/uriah/sites/www/fb/node_modules/webpack/lib/NormalModule.js:192:19)
    at /mnt/c/Users/uriah/sites/www/fb/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /mnt/c/Users/uriah/sites/www/fb/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/mnt/c/Users/uriah/sites/www/fb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/mnt/c/Users/uriah/sites/www/fb/node_modules/sass-loader/lib/loader.js:57:13)
    at Object.<anonymous> (/mnt/c/Users/uriah/sites/www/fb/node_modules/sass-loader/node_modules/async/dist/async.js:2243:31)
    at Object.callback (/mnt/c/Users/uriah/sites/www/fb/node_modules/sass-loader/node_modules/async/dist/async.js:906:16)
    at options.error (/mnt/c/Users/uriah/sites/www/fb/node_modules/node-sass/lib/index.js:294:32)

 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./resources/assets/js/app.js ./resources/assets/sass/app.scss

 error  in ./resources/assets/sass/app.scss

Module build failed: ModuleBuildError: Module build failed:
        font-weight: $weight-semibold;
                    ^
      Undefined variable: "$weight-semibold".
      in /mnt/c/Users/uriah/sites/www/fb/node_modules/buefy/src/scss/components/_dialog.scss (line 24, column 22)
    at runLoaders (/mnt/c/Users/uriah/sites/www/fb/node_modules/webpack/lib/NormalModule.js:192:19)
    at /mnt/c/Users/uriah/sites/www/fb/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /mnt/c/Users/uriah/sites/www/fb/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/mnt/c/Users/uriah/sites/www/fb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/mnt/c/Users/uriah/sites/www/fb/node_modules/sass-loader/lib/loader.js:57:13)
    at Object.<anonymous> (/mnt/c/Users/uriah/sites/www/fb/node_modules/sass-loader/node_modules/async/dist/async.js:2243:31)
    at Object.callback (/mnt/c/Users/uriah/sites/www/fb/node_modules/sass-loader/node_modules/async/dist/async.js:906:16)
    at options.error (/mnt/c/Users/uriah/sites/www/fb/node_modules/node-sass/lib/index.js:294:32)

 error

/mnt/c/Users/uriah/sites/www/fb/node_modules/extract-text-webpack-plugin/loader.js??ref--8-0!/mnt/c/Users/uriah/sites/www/fb/node_modules/style-loader/index.js!/mnt/c/Users/uriah/sites/www/fb/node_modules/css-loader/index.js??ref--8-2!/mnt/c/Users/uriah/sites/www/fb/node_modules/postcss-loader/index.js??ref--8-3!/mnt/c/Users/uriah/sites/www/fb/node_modules/resolve-url-loader/index.js?sourceMap!/mnt/c/Users/uriah/sites/www/fb/node_modules/sass-loader/lib/loader.js??ref--8-5!/mnt/c/Users/uriah/sites/www/fb/resources/assets/sass/app.scss doesn't export content

```

if i uncommented  this line from _core.scss it will not give error...
but of course i didnt have the buefy scss
```
@import "~buefy/src/scss/buefy";
```

I think this is a missing variable in your package can you check it?

**Comment by codeitlikemiley** [comment]
The only fix i made was to create this custom varible from within my _core.scss

```
$weight-semibold: "bolder";
```

**Comment by rafaelpimpa** [comment]
That's weird, that variable is from [Bulma itself](https://github.com/jgthms/bulma/blob/master/sass/utilities/initial-variables.sass#L41), shouldn't be a problem. Maybe some issue with laravel-mix?

**Comment by codeitlikemiley** [comment]
it seems it cant find that variable... so it cant build the app.scss 
yeah its really weird since you already imported bulma css...

**Comment by rafaelpimpa** [comment]
I'll close this since you already solved it and I have no idea on how to fix.
